#!/bin/bash
set -ef -o pipefail

export NODE_OPTIONS="${NODE_OPTIONS} --import /opt/loader.mjs --import /var/task/instrumentation.mjs"

if [[ $OTEL_RESOURCE_ATTRIBUTES != *"service.name="* ]]; then
  export OTEL_RESOURCE_ATTRIBUTES="service.name=${AWS_LAMBDA_FUNCTION_NAME},${OTEL_RESOURCE_ATTRIBUTES}"
fi

exec "$@"
